"""initial

Revision ID: cf139bc6fb00
Revises: 
Create Date: 2026-07-03 21:13:54.580784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf139bc6fb00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('letterboxd_slug', sa.String(), nullable=True),
    sa.Column('letterboxd_uri', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('original_title', sa.String(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('runtime_min', sa.Integer(), nullable=True),
    sa.Column('original_language', sa.String(), nullable=True),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('backdrop_path', sa.String(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('tmdb_fetched_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.create_index('idx_films_slug', ['letterboxd_slug'], unique=False)
        batch_op.create_index('idx_films_title', ['title'], unique=False)
        batch_op.create_index('idx_films_year', ['release_year'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value_json', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('subscriptions',
    sa.Column('provider_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.Column('monthly_cost_pence', sa.Integer(), nullable=True),
    sa.Column('active', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('added_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('letterboxd_username', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('letterboxd_username')
    )
    op.create_table('availability',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('region', sa.String(), server_default=sa.text("'GB'"), nullable=False),
    sa.Column('fetched_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("kind IN ('flatrate','free','ads','rent','buy')", name='ck_availability_kind'),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.PrimaryKeyConstraint('film_id', 'provider_id', 'kind', 'region')
    )
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.create_index('idx_availability_fetched', ['fetched_at'], unique=False)

    op.create_table('feedback_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("context IN ('rec','search','poster_wall','prompt','import')", name='ck_feedback_events_context'),
    sa.CheckConstraint("event_type IN ('rating','like','seen','not_interested','snooze','clicked','watchlisted','prompt_answer')", name='ck_feedback_events_event_type'),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback_events', schema=None) as batch_op:
        batch_op.create_index('idx_feedback_film', ['film_id'], unique=False)
        batch_op.create_index('idx_feedback_user_time', ['user_id', 'created_at'], unique=False)

    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_requested', sa.String(), nullable=False),
    sa.Column('source_used', sa.String(), nullable=True),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'running'"), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('started_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('finished_at', sa.String(), nullable=True),
    sa.Column('counts_json', sa.String(), nullable=True),
    sa.Column('cascade_json', sa.String(), nullable=True),
    sa.Column('export_zip_path', sa.String(), nullable=True),
    sa.Column('export_sha256', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.CheckConstraint("source_requested IN ('auto','export','export-upload','scrape','rss')", name='ck_import_runs_source_requested'),
    sa.CheckConstraint("source_used IN ('export','export-upload','scrape','rss')", name='ck_import_runs_source_used'),
    sa.CheckConstraint("status IN ('running','done','done_unchanged','failed')", name='ck_import_runs_status'),
    sa.CheckConstraint("trigger IN ('schedule','api','upload','drop_folder')", name='ck_import_runs_trigger'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_runs', schema=None) as batch_op:
        batch_op.create_index('idx_import_runs_user', ['user_id', 'started_at'], unique=False)

    op.create_table('letterboxd_log_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('finished_at', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('queued','running','done','failed','fallback_shown')", name='ck_letterboxd_log_jobs_status'),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("source IN ('letterboxd-import','letterboxd-scrape','letterboxd-rss','in-app')", name='ck_likes_source'),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'film_id')
    )
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('container', sa.String(), nullable=True),
    sa.Column('video_codec', sa.String(), nullable=True),
    sa.Column('audio_codec', sa.String(), nullable=True),
    sa.Column('jellyfin_item_id', sa.String(), nullable=True),
    sa.Column('scanned_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.create_index('idx_media_film', ['film_id'], unique=False)

    op.create_table('model_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('metrics_json', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('trained_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("kind IN ('feature_matrix','vocab','taste_model','item_embeddings','rec_snapshot')", name='ck_model_artifacts_kind'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_artifacts', schema=None) as batch_op:
        batch_op.create_index('idx_artifacts_kind_active', ['kind', 'is_active'], unique=False)

    op.create_table('ratings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('rated_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("source IN ('letterboxd-import','letterboxd-scrape','letterboxd-rss','in-app')", name='ck_ratings_source'),
    sa.CheckConstraint('rating >= 0.5 AND rating <= 5.0', name='ck_ratings_rating_range'),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'film_id')
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index('idx_ratings_film', ['film_id'], unique=False)

    op.create_table('recommendations_cache',
    sa.Column('profile', sa.String(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('components_json', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('generated_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.PrimaryKeyConstraint('profile', 'film_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('revoked', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_refresh_user', ['user_id', 'revoked'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.String(), nullable=False),
    sa.Column('contains_spoilers', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('watched_date', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("source IN ('letterboxd-import','letterboxd-scrape','letterboxd-rss','in-app')", name='ck_reviews_source'),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('idx_reviews_user_film', ['user_id', 'film_id'], unique=False)

    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cursor', sa.String(), nullable=True),
    sa.Column('last_run_at', sa.String(), nullable=True),
    sa.Column('last_ok_at', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('detail_json', sa.String(), nullable=True),
    sa.CheckConstraint("kind IN ('rss','csv_import','letterboxd_export','letterboxd_scrape','availability_refresh','retrain','backup','letterboxd_log')", name='ck_sync_state_kind'),
    sa.CheckConstraint("status IN ('ok','running','error')", name='ck_sync_state_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'user_id', name='uq_sync_state_kind_user')
    )
    op.create_table('unmatched_imports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('raw_row_json', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('letterboxd_uri', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('matched_film_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("status IN ('pending','matched','ignored')", name='ck_unmatched_imports_status'),
    sa.ForeignKeyConstraint(['matched_film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unmatched_imports', schema=None) as batch_op:
        batch_op.create_index('idx_unmatched_status', ['status'], unique=False)

    op.create_table('watches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('watched_date', sa.String(), nullable=True),
    sa.Column('rewatch', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tags_json', sa.String(), nullable=True),
    sa.Column('source', sa.String(), server_default=sa.text("'letterboxd-import'"), nullable=False),
    sa.Column('letterboxd_guid', sa.String(), nullable=True),
    sa.Column('letterboxd_uri', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("source IN ('letterboxd-import','letterboxd-scrape','letterboxd-rss','in-app')", name='ck_watches_source'),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('letterboxd_guid')
    )
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.create_index('idx_watches_date', ['user_id', 'watched_date'], unique=False)
        batch_op.create_index('idx_watches_user_film', ['user_id', 'film_id'], unique=False)

    # ### end Alembic commands ###

    # Expression-based unique index (docs/DATA_MODEL.md §2) — SQLAlchemy's SQLite
    # dialect can't reflect/autogenerate expression indexes (see the autogenerate
    # warning when this migration was generated), so it's added by hand here. This
    # is the load-bearing dedup key for CSV re-import idempotency.
    op.execute(
        "CREATE UNIQUE INDEX idx_watches_dedup "
        "ON watches(user_id, film_id, ifnull(watched_date,''))"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS idx_watches_dedup")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.drop_index('idx_watches_user_film')
        batch_op.drop_index('idx_watches_date')

    op.drop_table('watches')
    with op.batch_alter_table('unmatched_imports', schema=None) as batch_op:
        batch_op.drop_index('idx_unmatched_status')

    op.drop_table('unmatched_imports')
    op.drop_table('sync_state')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('idx_reviews_user_film')

    op.drop_table('reviews')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index('idx_refresh_user')

    op.drop_table('refresh_tokens')
    op.drop_table('recommendations_cache')
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index('idx_ratings_film')

    op.drop_table('ratings')
    with op.batch_alter_table('model_artifacts', schema=None) as batch_op:
        batch_op.drop_index('idx_artifacts_kind_active')

    op.drop_table('model_artifacts')
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_index('idx_media_film')

    op.drop_table('media_files')
    op.drop_table('likes')
    op.drop_table('letterboxd_log_jobs')
    with op.batch_alter_table('import_runs', schema=None) as batch_op:
        batch_op.drop_index('idx_import_runs_user')

    op.drop_table('import_runs')
    with op.batch_alter_table('feedback_events', schema=None) as batch_op:
        batch_op.drop_index('idx_feedback_user_time')
        batch_op.drop_index('idx_feedback_film')

    op.drop_table('feedback_events')
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_index('idx_availability_fetched')

    op.drop_table('availability')
    op.drop_table('users')
    op.drop_table('subscriptions')
    op.drop_table('settings')
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.drop_index('idx_films_year')
        batch_op.drop_index('idx_films_title')
        batch_op.drop_index('idx_films_slug')

    op.drop_table('films')
    # ### end Alembic commands ###
